# These are supported funding model platforms

github: [follow-prince]
open_collective: elavarasan
ko_fi: follow-prince    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Hook
        run: curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_HtrwqrRp0EJM5Y4FrP7mnroUxd0Q/k7FqhccfvO"